#' Calculate and index Relative Abundances (eDNA Index).
#'
#' @description
#' The following function will calculate relative abundance (RA) and the index
#' of relative abundance (RA_Index) for any data set. The RA_Index is identical
#' to eDNA Index, Double transformation, and Wisconsin transformation.
#' This function will also handle extreme values to falls outside a given
#' percentile. Extreme will otherwise have a big impact on the index,
#' that is based on the population max.
#' 
#' @param data (Required) Tidy data object.
#' @param sample (Required) Data variable with sample ID.
#' @param taxa (Required) Data variable with taxa ID.
#' @param abundance (Required) Data variable with sequence read counts (raw or rarefied).
#' @param ... (Optional) Other sample data variables to be preserved.
#' @param na.rep (Optional) Value to replace NA in abundance variable. Default: 0.
#' @param extreme.perc (Optional) Value defining upper percentile for extreme values. Default: 0.99. If no adjustment wanted: 1.
#' @value Same data class as input.
#' 
#' @example
#' df_18S %>% index_RA(
#'    sample = Library_ID,
#'    taxa = Genus,
#'    abundance = Abundance,
#'    Depth, Date)

index_RA <- function(data, sample, taxa, abundance, ...,
                     na.rep = 0, extreme.perc = 0.99) {
  
  output <- data %>%
    
    # 1. Replace NA
    mutate("{{abundance}}" := ifelse(is.na({{abundance}}),
                                     na.rep,
                                     {{abundance}})) %>% 
    
    # 2. Summaries abundance per sample and taxa
    group_by({{sample}}, {{taxa}}, ...) %>% 
    summarise("{{abundance}}" := sum({{abundance}})) %>% 
    
    # 3. Calculate relative abundance (RA) for each sample
    group_by({{sample}}, ...) %>% 
    reframe(RA = {{abundance}} / sum({{abundance}}),
            {{taxa}}, {{abundance}}) %>%
    filter(is.na(RA) == FALSE) %>% 
    
    # 4. Remove extreme values of relative abundance
    # Extreme values are defined by percentile, and temporally assigned -1
    group_by({{taxa}}) %>%
    reframe(RA = ifelse(RA <= quantile(RA, extreme.perc), RA, -1),
            {{sample}}, {{abundance}}, ...) %>%
    # Extreme values (assigned -1) are reassigned to the new maximum value.
    group_by({{taxa}}) %>%
    reframe(RA = ifelse(RA == -1, max(RA), RA),
            {{sample}}, {{abundance}}, ...) %>% 
    
    # 5. Calculate indexed relative abundance per taxa.
    group_by({{taxa}}) %>%
    reframe({{abundance}}, RA, RA_Index = RA/max(RA),
            {{sample}}, ...) %>% 
    filter(is.na(RA_Index) == FALSE) %>% 
    
    # 6. Arrange columns:
    select({{sample}}, ..., {{taxa}}, {{abundance}}, RA, RA_Index)

}





#' The following function will generate a list of prevalent species by
#' filtering the output generated by the function above. The function will
#' remove species with inadequate species names, and remove species with
#' generally low occurrences throughout the data set.

getSpeciesList <- function(data, type = "DNA") {
  # This function require the output of "collapseRAindex" function.
  
  # Prefiltration for DNA data.
  # An initial filtering step will remov any low observation.
  if (type == "DNA") {data <- filter(data, Abundance > 50)}
  
  List <- data %>% 
    
    # Remove low occurrences.
    # Each species has to be observed in more than 2 samples.
    filter(RA_Index > 0) %>% 
    group_by(Taxa) %>%
    filter(n() > 2) %>% 
    
    # Remove bad species names:
    # The following name patterns indicate that species level identification failed. 
    filter(!grepl('sp.', Taxa),
           !grepl('_sp', Taxa),
           !grepl(' sp', Taxa),
           grepl(' ', Taxa),
           is.na(Taxa)==FALSE,
           Taxa != "no identification") %>%
    
    # Special case database name correction:
    mutate(Taxa = ifelse(Taxa== "Discoconchoecia aff. elegans CMARA05309_Os109.1.1",
                         "Discoconchoecia elegans", Taxa)) %>% 
    
    # Get Taxa names
    pull(Taxa) %>% unique()
  
  return(List)  
  # This function returns a name vector of species that passed filtering parameters.
  
}




#' The following function will generate a list of prevalent genera by
#' filtering the output generated by the function above. The function
#' will remove genera with inadequate genus names, and remove genera with
#' generally low occurrences throughout the data set.


getGenusList <- function(data, type="DNA") {
  # This function require the output of "collapseRAindex" function.
  
  # Prefiltration for DNA data.
  # An initial filtering step will remove any low observation.
  if (type == "DNA") {data <- filter(data, Abundance > 50)}
  
  List <- data %>%
    
    # Remove low occurrences
    # Each genus has to be observed in more than 5 samples.
    filter(RA_Index > 0) %>% 
    group_by(Taxa) %>%
    filter(n() > 5) %>%
    
    # Remove bad genus names
    # The following name patterns indicate that genus level identification failed. 
    filter(is.na(Taxa)==FALSE,
           !grepl('_', Taxa),
           Taxa != "no identification",
           Taxa != "unknown genus") %>% 
    # Get Taxa names
    pull(Taxa) %>% unique()
  
  return(List)  
  # This function returns a name vector of genera that passed filtering parameters.
}

